project_name: certs-maker
version: 2
builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags:
        - -X "github.com/{{ tolower .Env.GITHUB_REPOSITORY }}/internal/version.Version={{ .Tag }}"
    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]
    goarm:
      - "7"
      - "6"

dockers:

  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-amd64-{{ .Tag }}"
    dockerfile: docker/Dockerfile.goreleaser
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-arm64-{{ .Tag }}"
    dockerfile: docker/Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv7-{{ .Tag }}"
    dockerfile: docker/Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv6-{{ .Tag }}"
    dockerfile: docker/Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"


docker_manifests:
  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-amd64-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-arm64-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv7-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv6-{{ .Tag }}"
    skip_push: "false"

  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-amd64-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-arm64-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv7-{{ .Tag }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:linux-armv6-{{ .Tag }}"
    skip_push: "false"
