name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
env:
  GO_VERSION: "1.23.0"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: |
          success() && (startsWith(github.ref, 'refs/tags/') ||
           (github.event_name == 'workflow_dispatch'))
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
